---
openapi: 3.0.3
info:
  title: ref-api
  description: Public API for ref-api
  version: "6"
paths:
  /mfc/transportexecutor/shuffles:
    post:
      tags:
        - transport-executor
      operationId: add-shuffles
      summary: Requests the execution of multiple shuffle transports.
      description: Requests the execution of multiple shuffle transports. All members
        of the transport list will be confirmed individually via the TransportInitiator
        interface.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddShufflesCommand"
      responses:
        "201":
          description: Created
components:
  schemas:
    AddShufflesCommand:
      description: Requests the execution of multiple shuffle transports. All members
        of the transports list will be confirmed individually via the TransportInitiator
        interface.
      x-horizon-topic-name: "${subsystem.bid}.mfc.main.cmd"
      required:
        - shuffles
      type: object
      properties:
        shuffles:
          description: Shuffle transports for multiple reference transports
          minItems: 1
          type: array
          items:
            $ref: "#/components/schemas/AddShufflesDto"
        confirmationChannel:
          description: Channel provided by an external SCM.
          type: string
          example: tas.transporttask.cmd
    AddShufflesDto:
      description: Represents the shuffle transports realated to a reference transport.
      type: object
      properties:
        transports:
          description: List shuffle transports which must be executed before the reference
            transport can be executed.
          type: array
          items:
            $ref: "#/components/schemas/TransportDto"
    TransportDto:
      description: "Representation of the data of a transport to be executed, in the\
        \ form of a DTO."
      required:
        - transportUnit
      type: object
      properties:
        transportUnit:
          description: The transport unit that shall be moved with this transport.
          type: object
          allOf:
          - $ref: "#/components/schemas/TransportUnitDto"
    TransportUnitDto:
      description: This value object contains transport unit related data.
      type: object
      properties:
        destinationLocationId:
          description: Destination location identifier
          type: string
          allOf:
            - $ref: "#/components/schemas/LocationId"
          example: "1200"
          default: "123"
        xExtension:
          description: "Dynamic dimension: TU extension along X-Axis of equipment\
            \ system, usually in mm."
          type: number
          allOf:
            - $ref: 'types-api.yaml#/components/schemas/LengthSimpleType'
          example: 1200
          default: 123
    LocationId:
      description: The identifying value for a location.
      type: string
      example: BHB.UL50.51.0.UL51100201
      x-horizon-simpletype: true

