### inb-api ###
# This is the API descriptor for the inb-api. It is used to generate the API documentation for the inb-api.
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "inb-api"
  description: Public API for inb-api
  tags:
    - rest
    - api-documentation
    - api
    - openapi
    - inb-api
  links:
    - url: https://gitlab.com/dematic/horizon/apis
      icon: help
      title: Horizon OpenAPI monorepo in GitLab

spec:
  type: openapi
  lifecycle: production
  owner: Horizon
  definition:
    $openapi: ./inb-api.yaml

