openapi: 3.0.0
info:
  title: Vehicle Search
  description: |
    The Vehicle search API
  version: 1.0.0-Draft
servers:
  - url: test@example.com
tags:
  - name: Vehicle Search
    description: APIs to query vehicle properties and vehicle model.
paths:
  /vehicles/brands2:
    get:
      summary: Lists all available brands2
      operationId: vehicleBrands2
      responses:
        '700':
          $ref: '#/components/responses/WorkflowError'
      tags:
        - Vehicle Search
  /vehicles/brands:
    get:
      summary: Lists all available brands
      operationId: vehicleBrands
      responses:
        '200':
          description: Returns the list of brands
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataOptionList'
        '400':
          $ref: '#/components/responses/ClientError'
        '500':
          $ref: '#/components/responses/ServerError'
        '700':
          $ref: '#/components/responses/WorkflowError'
      tags:
        - Vehicle Search
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 100
          maximum: 599
          example: 503
        title:
          type: string
          description: A short, summary of the problem type. Written in english and readable for engineers.
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
    VehicleData:
      type: object
      required:
        - label
        - value
      properties:
        label:
          type: string
          example: label
        value:
          type: string
          example: value
        additionalText:
          type: string
    DataOptionList:
      type: object
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/VehicleData'
  responses:
    WorkflowError:
      description: Server side error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: 700
            title: Internal Workflow Error
            detail: Maximum invoke depth has been reached
    ClientError:
      description: Client side error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: 400
            title: Bad request
            detail: Validation failed
    ServerError:
      description: Server side error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: 500
            title: Internal Server Error
            detail: Failed to map model
