openapi: 3.0.0
info:
  title: Vehicle Search
  description: |
    The Vehicle search API
  version: 1.0.0-Draft
tags:
  - name: Vehicle Search
    description: APIs to query vehicle properties and vehicle model.
servers:
  - url: test@example.com
paths:
  /vehicles/brands:
    get:
      summary: Lists all available brands
      operationId: vehicleBrands
      responses:
        "200":
          description: Returns the list of brands
          content:
            application/json:
              schema:
                $ref: "models.yaml#/components/schemas/DataOptionList"
        "400":
          $ref: "models.yaml#/components/responses/ClientError"
        "500":
          $ref: "models.yaml#/components/responses/ServerError"
      tags:
        - Vehicle Search
