### fop-api ###
# This is the API descriptor for the fop-api. It is used to generate the API documentation for the fop-api.
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "fop-api"
  description: Public API for fop-api
  tags:
    - rest
    - api-documentation
    - api
    - openapi
    - fop-api
  links:
    - url: https://gitlab.com/dematic/horizon/apis
      icon: help
      title: Horizon OpenAPI monorepo in GitLab

spec:
  type: openapi
  lifecycle: production
  owner: Horizon
  definition:
    $openapi: ./fop-api.yaml

